FROM golang:1.18-alpine

ENV GO111MODULE=on \
  CGO_ENABLED=0 \
  GOOS=linux \
  GOARCH=amd64

WORKDIR /app

COPY ./src/go.mod ./
COPY ./src/go.sum ./

RUN go mod download

COPY ./src .

RUN go build -o ./app .

EXPOSE 8080

CMD [ "./app" ]