version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dojo
    ports: 
      - '5432:5432'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - 'db:/var/lib/postgresql/data'
  users:
    build:
      context: ./users
    volumes:
      - ./users/src:/usr/app
    ports:
      - "3001:3001"
  todos:
    build:
      context: ./todos
    volumes:
      - ./todos:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3002:3002"
    command: npm run start
  client:
    build:
      context: ./client
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run start
volumes:
  db:
networks:
  default:
    name: dojo-network